config/routes.rb
Rails.application.routes.draw do
  resources :pastes

  root 'pastes#index'
  mount Resque::Server, :at => "/resque"

end

app/models/paste.rb
class Paste < ActiveRecord::Base
	validates :content, :presence => true
	#Make content must
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pastes_controller.rb
class PastesController < ApplicationController
  before_action :set_paste, only: [:show, :edit, :update, :destroy]

  # GET /pastes
  # GET /pastes.json
  def index
    @pastes = Paste.all
    @paste = Paste.new

  end

  # GET /pastes/1
  # GET /pastes/1.json
  def show
  end

  # GET /pastes/new
  def new
    @paste = Paste.new
  end

  # GET /pastes/1/edit
  def edit
  end

  # POST /pastes
  # POST /pastes.json
  def create
    @paste = Paste.new(paste_params)

    respond_to do |format|
      if @paste.save
        Resque.enqueue_at(15.minutes.from_now, PasteDeleter, @paste.id )
        #Resque.enqueue(PasteDeleter, @paste.id )
        format.html { redirect_to @paste, notice: 'Paste was successfully created.' }
        format.json { render :show, status: :created, location: @paste }
      else
        format.html { render :new }
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastes/1
  # PATCH/PUT /pastes/1.json
  def update
    respond_to do |format|
      if @paste.update(paste_params)
        format.html { redirect_to @paste, notice: 'Paste was successfully updated.' }
        format.json { render :show, status: :ok, location: @paste }
      else
        format.html { render :edit }
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastes/1
  # DELETE /pastes/1.json
  def destroy
    @paste.destroy
    respond_to do |format|
      format.html { redirect_to pastes_url, notice: 'Paste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paste
      @paste = Paste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paste_params
      params.require(:paste).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pastes_helper.rb
module PastesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pastebox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<nav class = "navbar navbar-default" role = "navigation">
 <div class = "navbar-header">
      <a class = "navbar-brand" href = "#">PasteBox</a>
   </div>

</nav>
<%= yield %>

</body>
</html>

app/views/pastes/_form.html.erb
<%= form_for(@paste) do |f| %>
  <% if @paste.errors.any? %>
    <div class="alert alert-danger">
      <%= pluralize(@paste.errors.count, "error") %> prohibited this paste from being saved:

      <ul>
      <% @paste.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.text_area :content, class:"form-control", size: "75x25" %>
  </div>
  <div class="actions">
    <%= f.submit 'submit' , class: "btn btn-default" %>
  </div>
<% end %>

app/views/pastes/edit.html.erb
<h1>Editing Paste</h1>

<%= render 'form' %>

<%= link_to 'Show', @paste %> |
<%= link_to 'Back', pastes_path %>

app/views/pastes/index.html.erb
<p id="notice" class="alert"><%= notice %></p>


<div class="row" id="#mainPage">
  <div class="col-md-8">
     Pastes will be deleted after 15 minutes
     <%= render 'form' %>
  </div>

  <div class="col-md-4">
<div class="listPasteHeader">Listing Pastes</div>
<table class="table ">
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pastes.each do |paste| %>
      <tr>
        <td><%= paste.id %></td>
        <td><%= link_to '', paste, class: "glyphicon glyphicon-zoom-in", :title => "Show" %></td>
        <td><%= link_to '', edit_paste_path(paste), class: "glyphicon glyphicon-pencil", :title => "Edit" %></td>
        <td><%= link_to '', paste, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove", :title => "Remove" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Paste', new_paste_path, class: "btn btn-default" %> -->
</div>
</div>

app/views/pastes/new.html.erb
<%= render 'form' %>

<%= link_to '', pastes_path, class: "glyphicon glyphicon-arrow-left", :title => "Back" %> 

app/views/pastes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
	<div class="panel-heading">
		<%= @paste.id %>		
	</div>
	 <div class="panel-body">
  	<%= @paste.content %>
  	</div>
</div>

<%= link_to '', pastes_path, class: "glyphicon glyphicon-arrow-left", :title => "Back" %> |
<%= link_to '', edit_paste_path(@paste),class: "glyphicon glyphicon-pencil", :title => "Edit" %>